name: Validate OSCAL Component Definition Schema
on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**.go"

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate Big Bang OSCAL component definition
      run: make

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11

    - name: Validate Schema with oscal-cli
      uses: oscal-club/oscal-cli-action@v1
      with:
        args: component-definition validate --as yaml oscal-component.yaml